76 autopipe
qurit/raiven pull request #123
Opened 2021-02-01 09:58 UTC by KlamChowder1

tried a few different approaches but ultimately went back to the way i did it before... still not sure if this is the best way to do it though :/ 

also was thinking of putting it in the pipeline builder page but not sure if that would clutter it up too much with too many buttons - so felt like having it in users settings is a nice central place to put it - but idk if maybe it should be in the DicomRuns page or elsewhere perhaps

![autopipe](https://user-images.githubusercontent.com/24284083/106443042-e4841000-6430-11eb-8803-895f80d24f2d.gif)
![image](https://user-images.githubusercontent.com/24284083/106443051-e6e66a00-6430-11eb-81e6-ff6d078c291b.png)

2021-02-08 08:15 UTC, KlamChowder1 commented
stores in db too now 

![autopipe_crud](https://user-images.githubusercontent.com/24284083/107192610-b196ca80-69a2-11eb-9d09-2952542b1e6b.gif)

2021-02-08 09:29 UTC, awtkns commented
@KlamChowder1 so what's missing now, just the actual pipelining integration?

2021-02-08 09:40 UTC, awtkns requested changes

2021-02-08 09:40 UTC, awtkns commented on backend/api/routes/pipeline.py
> +    return condition
Here we should be checking to see if the user has permissions to edit these conditions

2021-02-08 09:40 UTC, awtkns commented on backend/api/models/pipeline.py
> +    is_active = Column(Boolean)
What does is_active mean in this context?

2021-02-08 09:40 UTC, awtkns commented on frontend/store/conditions.js
> +
```suggestion
const URL = '/pipeline/condition'

```

2021-02-08 09:40 UTC, awtkns commented on frontend/store/conditions.js
> +      const URL = '/pipeline/condition'
```suggestion

```

2021-02-08 09:40 UTC, awtkns commented on frontend/store/conditions.js
> +      await generic_delete(this, URL)
```suggestion
      await generic_delete(this, `${URL}/${id}`)
```

2021-02-08 09:40 UTC, awtkns commented on frontend/store/conditions.js
> +      const URL = '/pipeline/condition'
```suggestion
```

2021-02-08 09:45 UTC, awtkns commented
> also was thinking of putting it in the pipeline builder page but not sure if that would clutter it up too much with too many buttons - so felt like having it in users settings is a nice central place to put it - but idk if maybe it should be in the DicomRuns page or elsewhere perhaps

We can talk an figure out a good place to put it

2021-02-09 08:13 UTC, KlamChowder1 commented on backend/api/models/pipeline.py
> +    is_active = Column(Boolean)
wasn't sure if we wanted to allow users to be able to turn on/off their conditional runs so I did a "is_active" flag to indicate if we should be checking for these conditions or not sort of thing - we could discuss this some more though

2021-02-09 08:14 UTC, KlamChowder1 commented on backend/api/routes/pipeline.py
> +    return condition
maybe we should link a Condition to a User ?

2021-02-09 08:16 UTC, KlamChowder1 commented
> @KlamChowder1 so what's missing now, just the actual pipelining integration?

yea - just need to figure out how to actually do the checking of conditions to send to a pipeline

2021-02-09 09:28 UTC, awtkns commented on backend/api/routes/pipeline.py
> +    return condition
The fastapi-crud router would almost be useful here haha

2021-02-11 23:12 UTC, KlamChowder1 commented
added the "subtype" to specify what property of node/patient/study/series we want to wait for before sending to a pipeline 

![autopipe-with-subtype](https://user-images.githubusercontent.com/24284083/107710305-8d293f80-6c7b-11eb-94a2-6a3f28991370.gif)

2021-02-11 23:15 UTC, awtkns commented
@KlamChowder1 I think we spent today working on the same thing LOL

2021-02-12 02:51 UTC, KlamChowder1 commented
@awtkns RIP :(

2021-02-13 03:51 UTC, awtkns commented
![image](https://user-images.githubusercontent.com/32209255/107840963-c04afc00-6d6b-11eb-8a49-6c3485866ea8.png)

2021-02-13 03:52 UTC, awtkns commented
![form3](https://user-images.githubusercontent.com/32209255/107840972-d658bc80-6d6b-11eb-92b2-2e0748d67bb8.gif)
 @KlamChowder1

2021-02-23 07:13 UTC, awtkns commented
Closed as features are moved to #134

2021-02-23 07:13 UTC, closed without merging