Return To Sender
qurit/raiven pull request #125
Opened 2021-02-04 19:44 UTC by awtkns

### Features:
- Adds the ability to send the output to the pipeline initator
- Numerous Refactors
- Removed the destination table

2021-02-05 19:54 UTC, asim-shrestha requested changes

2021-02-05 19:54 UTC, asim-shrestha commented on backend/api/pipelining/_tasks/run.py
> +                if dest.user.name == config.INTERNAL_USERNAME:
Maybe making another user for destinations would be cleaner. Then we can do.

`if dest.user.name == config.RTS_USERNAME:`

Alternatively could set `config.RTS_USERNAME = config.INTERNAL_USERNAME` in the config code as to not create a brand new user.

2021-02-05 19:54 UTC, asim-shrestha commented on backend/api/routes/user.py
Whats goin on with the two methods below?

2021-02-05 19:54 UTC, asim-shrestha commented on backend/tests/test_dicom/test_rts.py
> +            # TODO: COMPARE FILES
How come these are commented out?

2021-02-05 20:14 UTC, awtkns commented on frontend/utilities/validationRules.js
> +export const validatePort = v => /^([1-9]|[1-5]?[0-9]{2,4}|6[1-4][0-9]{3}|65[1-4][0-9]{2}|655[1-2][0-9]|6553[1-5])$/.test(v) || 'Field is not a valid port'
No but we should

2021-02-05 20:14 UTC, awtkns commented on backend/api/routes/dicom.py
> +    elif not db_node.output:
Yes that way we don't store it twice

2021-02-05 20:14 UTC, awtkns commented on backend/api/routes/user.py
We will need to talk with @KlamChowder1

2021-02-05 20:14 UTC, awtkns commented on backend/api/schemas/pipeline.py
> +    destination: Optional[DicomNode]
I think destination is better here. We are not actually referring to the node id but a nested object

2021-02-05 20:14 UTC, awtkns commented on backend/tests/test_dicom/conftest.py
> +    sleep(3)
```suggestion
```

pretty sure this can be removed actually

2021-02-09 20:24 UTC, awtkns commented on backend/api/pipelining/_tasks/run.py
> +        with worker_session() as db:
Because the send_dicom_folder(dest, folder) is a long running task that does not need a database connection

2021-02-09 20:28 UTC, awtkns commented on frontend/api/index.js
>  export const generic_get = async ({ $axios }, url, params) =>
I just refactored out all the dicom functionality to abstract it more

2021-02-11 18:17 UTC, asim-shrestha approved these changes
LGTM!

2021-02-11 18:17 UTC, merged