Ldap users
qurit/raiven pull request #147
Opened 2021-04-12 10:21 UTC by KlamChowder1

view LDAP users stuff 

![image](https://user-images.githubusercontent.com/24284083/114379805-1ce55000-9b3e-11eb-9939-0aaa4c0afb08.png)

2021-04-19 08:08 UTC, KlamChowder1 commented
- added access / admin controls to admin page 
![admin_and_access](https://user-images.githubusercontent.com/24284083/115202845-ad2a1480-a0ab-11eb-849e-fcf03c956995.gif)
- put file results in own page
![image](https://user-images.githubusercontent.com/24284083/115202884-b61ae600-a0ab-11eb-8722-c26c12828759.png)
![image](https://user-images.githubusercontent.com/24284083/115202898-b915d680-a0ab-11eb-80a9-f3e034c9f7f4.png)

2021-04-20 19:22 UTC, awtkns requested changes

2021-04-20 19:22 UTC, awtkns commented on backend/api/routes/user.py
> +    return user_to_change
```suggestion
@router.put("/modify-access/{user_id}", response_model=UserSchema, dependencies=[Depends(admin_auth)])
def modify_user_access(user_id: int, db: Session = Depends(session)):
    """ Change the user's access permissions """
    
    user_to_change = db.query(User).get(user_id)
    user_to_change.access_allowed = not user_to_change.access_allowed
    user_to_change.save(db)
    return user_to_change
```

2021-04-20 19:22 UTC, awtkns commented on backend/api/routes/user.py
> +    return user_to_change
You are going to want to check that the user_id exists, else 404

2021-04-21 01:56 UTC, KlamChowder1 commented
![image](https://user-images.githubusercontent.com/24284083/115485706-17f16200-a20a-11eb-833b-50bfc912e056.png)

- added type
- put all edit user settings stuff in one route

2021-04-27 17:47 UTC, awtkns approved these changes
LGTM 😄

2021-04-27 19:48 UTC, merged